[package]
versioned_files = ["Cargo.toml", { path = "Cargo.lock", dependency = "barnacle-rs" }]
changelog = "CHANGELOG.md"

[changesets]
dir = ".changeset"

[changes]
ignore_conventional_commits = true

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[github]
owner = "zyphelabs"
repo = "barnacle-rs"
